### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MartynasZilinskas** [reactway/forms#1]
- [ ] FieldState Data structure
  - [ ] [Main Field data structure](https://github.com/reactway/forms/issues/2)
- [ ] Store updaters
- [ ] Getting Field value
- [ ] Validation
- [ ] Field statuses update mechanism
- [ ] Register/Unregister Field
- [ ] Permanent Fields (do not destroy Field on unmount)
- [ ] Modifiers and Formatters (Normalizers)
- [ ] Group and ListGroup
- [ ] Field References
- [ ] Hydration/Dehydration
- [ ] Store Consumer Component
- [ ] Reset, Clear, Submit mechanism and buttons 
- [ ] Secondary event handlers (e.g. `onChange`, `onFocus`, etc. that are provided by user)
- [ ] Included DOM fields
  - [ ] `<input />`
    - [ ] Text
    - [ ] Password
    - [ ] Number
    - [ ] Radio
    - [ ] Checkbox
    - [ ] File
  - [ ] `<select />`
  - [ ] `<textarea />`
  - [ ] Buttons
    - [ ] Reset
    - [ ] Clear
    - [ ] Button? (maybe with a store as a second argument for `onClick`)
